apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ironic-shared-volume
  #annotations:
  #  "helm.sh/resource-policy": keep
spec:
  accessModes:
  - {{ .Values.persistence.ironic.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.ironic.size }}
  {{- if or .Values.global.storageClass .Values.persistence.ironic.storageClass }}
  storageClassName: {{ .Values.global.storageClass | default .Values.persistence.ironic.storageClass }}
  {{- end }}
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  #annotations:
  #  "helm.sh/resource-policy": keep
spec:
  accessModes:
  - {{ .Values.persistence.mariadb.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.mariadb.size }}
  {{- if or .Values.global.storageClass .Values.persistence.mariadb.storageClass }}
  storageClassName: {{ .Values.global.storageClass | default .Values.persistence.mariadb.storageClass }}
  {{- end }}
  volumeMode: Filesystem